# Generated by Django 2.1.5 on 2019-01-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='typeCat',
            field=models.CharField(choices=[('Professionnelles', 'Professionnelles'), ('Usuelles', 'Usuelles'), ('Loisirs', 'Loisirs'), ('Sportives', 'Sportives')], max_length=16),
        ),
    ]
