# Generated by Django 2.1.5 on 2019-01-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculdej', '0002_auto_20190120_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureeCont', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activiteCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculdej.Activite')),
                ('categorieCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculdej.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=30)),
                ('dernier', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contenu',
            name='dossierCont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculdej.Dossier'),
        ),
    ]
