# Generated by Django 2.1.5 on 2019-01-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0003_auto_20190120_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contenu',
            new_name='Travail',
        ),
        migrations.RenameField(
            model_name='travail',
            old_name='activiteCont',
            new_name='activiteTrav',
        ),
        migrations.RenameField(
            model_name='travail',
            old_name='categorieCont',
            new_name='categorieTrav',
        ),
        migrations.RenameField(
            model_name='travail',
            old_name='dossierCont',
            new_name='dossierTrav',
        ),
        migrations.RenameField(
            model_name='travail',
            old_name='dureeCont',
            new_name='dureeTrav',
        ),
    ]
