# Generated by Django 2.0 on 2019-01-29 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0004_auto_20190120_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='titre',
        ),
        migrations.AddField(
            model_name='dossier',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date création'),
        ),
    ]
