# Generated by Django 2.0 on 2019-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0005_auto_20190129_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossier',
            name='poids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sexe',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='dossier',
            name='taille',
            field=models.IntegerField(default=0),
        ),
    ]
