# Generated by Django 2.0 on 2019-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0006_auto_20190130_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='sexe',
            field=models.CharField(default='', max_length=1),
        ),
    ]
