# Generated by Django 2.0 on 2019-01-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0007_auto_20190130_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='taille',
        ),
        migrations.AddField(
            model_name='dossier',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
