# Generated by Django 2.1.5 on 2019-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0009_dossier_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='coef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
