# Generated by Django 2.1.5 on 2019-03-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0010_travail_coef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travail',
            old_name='coef',
            new_name='coefTrav',
        ),
    ]
