# Generated by Django 2.0 on 2019-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0011_auto_20190321_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='imc',
            new_name='poids',
        ),
        migrations.AddField(
            model_name='dossier',
            name='pathologie',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dossier',
            name='taille',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
