# Generated by Django 2.1.5 on 2019-03-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculdej', '0014_auto_20190329_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='det',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
